### ISSUE TITLE
getting a error in header bar 

### ISSUE THREAD

**Issue by joseph15562** [mathhulk/ab-web-addon#10]
getting a line error at the header bar 

Notice: Undefined index: HTTP_X_FORWARDED_PROTO in C:\xampp\htdocs\bans\index.php on line 125

[http://pradomic.co.uk/bans/error.png](url)

**Comment by mathhulk** [comment]
What version of PHP are you using? Please try updating if you are not using the latest version.

**Comment by joseph15562** [comment]
Doing that now il get back to you when it's done

**Comment by joseph15562** [comment]
updated and still the same sorry it took me a while all the databases broke so had to remake each one for mc stuff

**Comment by mathhulk** [comment]
Are you using the latest version of ab-web-addon?

**Comment by mathhulk** [comment]
Should be fixed.
