### ISSUE TITLE
List the types of punishments issue.

### ISSUE THREAD

**Issue by salasan1** [mathhulk/ab-web-addon#12]
`$types = array('kaikki','porttikielto','temp_ban','mute','temp_mute','warning','temp_warning','kick');`
and it looks like [this](http://i.imgur.com/mRVuM6E.png) so problem is if i change that ban to porttikielto it will shows that 0 player is banned so what is problem?

**Comment by mathhulk** [comment]
The problem is that AdvancedBan does not support multiple languages for punishments.

**Comment by salasan1** [comment]
so you cant do anythink to that problem no methods?

**Comment by mathhulk** [comment]
Will be fixed in the next update when I add a language file.

**Comment by mathhulk** [comment]
Going to keep this open as a reminder.
