### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by donleo123** [mathhulk/ab-web-addon#2]
Getting this:

Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in /home/u895902253/public_html/bans/index.php on line 71

Line 71: $result = mysqli_query($con,"SELECT * FROM `".$info['table']."".strtoupper($type).""); $rows = mysqli_num_rows($result); //Grab the number of rows per punishment type.

**Comment by mathhulk** [comment]
What version of PHP are you using?

**Comment by donleo123** [comment]
5.6.21

**Comment by mathhulk** [comment]
Try upgrading to the latest version of PHP and see if that fixes your issue, @donleo123.

**Comment by mathhulk** [comment]
This should be fixed in the latest version. If not, please create another issue.
