### ISSUE TITLE
Unauthenticated Scripts Error

### ISSUE THREAD

**Issue by Spazzinq** [mathhulk/ab-web-addon#23]
![image](https://user-images.githubusercontent.com/26337405/32151678-29dfe2a0-bcf5-11e7-9c7f-2b2d2c672812.png)

**Comment by mathhulk** [comment]
Are you using the latest version of ab-web-addon? I don't use `use.gameapis.net` anywhere in ab-web-addon. Along with this, I get no insecure content warnings on https://www.mathhulk.me/github/ab-web-addon/, which is the latest version of ab-web-addon.

**Comment by Spazzinq** [comment]
Closed as I could not reproduce the issue anymore
