### ISSUE TITLE
Https not working

### ISSUE THREAD

**Issue by lucas2107** [mathhulk/ab-web-addon#31]
Hi,

Since your last update, https isn't working: https://bans.chocolia.eu/
I've tried to set https to true in your config, it don't work.

Best regards,

EDIT: Error 500 with default config
http://145.239.0.71/chocolia/banlist/

**Comment by mathhulk** [comment]
I will be looking into this as soon as I can. Thank you for the report. I have the default configuration running on https://mathhulk.me/github/ab-web-addon, so I will try to reproduce the issue later today.

**Comment by mathhulk** [comment]
@lucas2107, the HTTPS option in the configuration file is only used for meta tags. Everything else should work on HTTPS whether the HTTPS option in the configuration file is set to true or not. I am using the latest update (latest commit) version of ab-web-addon on https://mathhulk.me/github/ab-web-addon with HTTPS set to false in the configuration file and everything is working fine.

**Comment by lucas2107** [comment]
I don't know why I've error 500 :/
I'm using php 7.0

**Comment by mathhulk** [comment]
I am using PHP 7 also. Are you sure that you downloaded ab-web-addon recently?

**Comment by lucas2107** [comment]
Hi,

I've re-downloaded the addon, with default config with my database infos, error 500.
Nothing in the error.log from apache :/

**Comment by mathhulk** [comment]
Open /index.php with a text editor and replace `error_reporting(0);` with `error_reporting(E_ALL)`. Then, tell me what errors you find in the error file in the root directory of ab-web-addon.

**Comment by mathhulk** [comment]
This should be fixed in the latest update. GitHub did not seem to recognize the change in capitalize of a file or I must have forgot to capitalize it on my computer when I moved the files to be pushed to GitHub.
