### ISSUE TITLE
Error in graphs.php

### ISSUE THREAD

**Issue by lucas2107** [mathhulk/ab-web-addon#32]
Hi,

In my error.log: https://hastebin.com/epazabatal.pas

Banlist working here: http://145.239.0.71/chocolia/banlist/
But not with my domain... https://bans.chocolia.eu/ <-- No error for this :/

Best regards,

**Comment by mathhulk** [comment]
I will look into the graphs error as soon as I get home. 

Also, bans.chocolia.eu does not resolve to an IP address, so I am assuming that it is not setup correctly as a sub-domain. That’s the reason you aren’t getting errors.

**Comment by mathhulk** [comment]
The graph error should be fixed. A variable name was incorrect.
