### ISSUE TITLE
Add cache for player heads

### ISSUE THREAD

**Issue by lucas2107** [mathhulk/ab-web-addon#33]
Add a temp cache ( 7 days ?) for players head.

**Comment by mathhulk** [comment]
I will look into this. Please review the latest update for recent API and head/skull changes.

**Comment by lucas2107** [comment]
Nice change about heads, but so long to load, that's why you need to add a cache for this ^^

**Comment by mathhulk** [comment]
I understand. I will look into a similar concept when I get a chance.

**Comment by mathhulk** [comment]
I probably won't be adding complete support for skulls at this time, as I'm having trouble finding a reliable API. You can look at the other issue you created for more information.
#35
