### ISSUE TITLE
Timezone doesn't work

### ISSUE THREAD

**Issue by derrodirik** [mathhulk/ab-web-addon#4]
The geoip function doesn't work for me I see nothing on the page and this in the log:

`PHP Fatal error:  Call to a member function format() on null in /var/www/html/banpage/index.php on line    136, referer: https://gc.roethke.info/banpage/index.php?type=ban`

**Comment by mathhulk** [comment]
What PHP version are you using?

**Comment by derrodirik** [comment]
5.6.30-0

**Comment by mathhulk** [comment]
Try updating to the latest version and see if that solves your problem, @derrodirik. Not sure why this is happening, though, as I am using version 5.4.

**Comment by mathhulk** [comment]
Please check the latest update @derrodirik.
