### ISSUE TITLE
Head/Body API NOT WORKING

### ISSUE THREAD

**Issue by ToMmysek795** [mathhulk/ab-web-addon#43]
Hello, i want a reason, why Heads on Banlist are not working?
![snimek z 2018-03-15 07-08-54](https://user-images.githubusercontent.com/21044779/37446933-b26e2fce-281f-11e8-84f3-bb2318831175.png)

**Comment by ToMmysek795** [comment]
It gets Steve UUID, but NO UUID of player.

What are the UUID servers when they are worthless?

**Comment by ToMmysek795** [comment]
Any PHP code for that?

**Comment by mathhulk** [comment]
It seems that Mojang's server were down for some time. I think this was a temporary problem.
