### ISSUE TITLE
Nginx web

### ISSUE THREAD

**Issue by BJPGameVideosITA** [mathhulk/ab-web-addon#46]
I cloned the repository on my VPS which is running nginx on linux ubuntu 16.04.4 LTS and I always get error 500.
I tried putting it both on folder and on subdomain, none works out.
My site is hosted right now at http://www.bjphoster.com/banlist and at http://ban.bjphoster.com - to be noted: DNS does not work yet at the date of the message because of a DNS Server issue with registrar servers; working on that right now. (the site is also always accessible at 185.25.207.114, to try the subdomain you can use either /etc/hosts or C:\Windows\System32\drivers\etc\hosts, dependently on which OS you are using) - https://goo.gl/8oChCh
Thanks;
Bryan.

**Comment by mathhulk** [comment]
The master branch of ab-web-addon does not contain the latest release, but rather is being used for the development of major updates for ab-web-addon. The repository is not ready for production in any way at all and has no support for Nginx even if you tried to clone it. As of right now, it only supports Apache with .htaccess. When the major updates for ab-web-addon are released, support for Nginx will come with it.

If you are looking to use ab-web-addon in a production environment, please download the latest release from SpigotMC or from the releases page.
