### ISSUE TITLE
Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in /data/web/virtuals/137665/virtual/www/banlist/index.php on line 159

### ISSUE THREAD

**Issue by InfinCZ** [mathhulk/ab-web-addon#8]
Hello,
plese help with message: 

Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in /data/web/virtuals/137665/virtual/www/banlist/index.php on line 159

and 

Fatal error: Uncaught Error: Call to undefined function mysql_error() in /data/web/virtuals/137665/virtual/www/banlist/index.php:189 Stack trace: #0 {main} thrown in /data/web/virtuals/137665/virtual/www/banlist/index.php on line 189

Here is image: 

https://s3.postimg.org/g9ujptphf/error.png
https://s4.postimg.org/ytcxb4afh/error2.png
https://s24.postimg.org/lwit2i9kl/error3.png

Thanks,  Infin

**Comment by mathhulk** [comment]
What version of PHP are you using? Please try updating.

**Comment by InfinCZ** [comment]
I use PHP 7.0

**Comment by InfinCZ** [comment]
?

**Comment by mathhulk** [comment]
Are you using the latest stable version of PHP 7? I don't think ab-web-addon has been tested with PHP 7+ anyways, as I use 5.4 for testing. However, it should work with newer versions.

**Comment by InfinCZ** [comment]
I change PHP to 5.4 , but still it shows,

**Comment by mathhulk** [comment]
Are you using the latest version of ab-web-addon? I have had no problems with this myself and am confused on where your second error is coming from. mysql_error() should never have been called.

**Comment by InfinCZ** [comment]
I use latest version.
And below i an error "Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in /data/web/virtuals/137665/virtual/www/banlist/index.php on line 218"

**Comment by InfinCZ** [comment]
OK I reinstall this application and all is ok, soryy.

Thanks

Infin
